spring:
  datasource:
    username: radb
    password: radb
    url: jdbc:mysql://martins.c1hfoaookicx.us-east-1.rds.amazonaws.com:3306/radb

eureka:
  client:
    service-url:
      defaultZone: http://ra-eureka-server:8761/eureka