spring:
  datasource:
    username: radb
    password: radb
    url: jdbc:mysql://martins.c1hfoaookicx.us-east-1.rds.amazonaws.com:3306/radb
  cloud:
    gateway:
      routes:
        - id: app-exame
          uri: http://svc-app-exame/
          predicates:
            - Path=/exame/**
        - id: app-usuario
          uri: http://svc-app-usuario/
          predicates:
            - Path=/usuario/**
        - id: app-servicosaude
          uri: http://svc-app-servicosaude/
          predicates:
            - Path=/servico-saude/**


eureka:
  client:
    service-url:
      defaultZone: http://svc-eureka-server/eureka
