spring:
  cloud:
    gateway:
      routes:
        - id: app-exame
          uri: http://localhost:8080/
          predicates:
            - Path=/exame/**
        - id: app-usuario
          uri: http://localhost:8081/
          predicates:
            - Path=/usuario/**
        - id: app-servicoSaude
          uri: http://localhost:8082/
          predicates:
            - Path=/servico-saude/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
